[project]
name = "ts-profiler"
version = "0.0.1"
description = "Time series profiling workspace"
authors = [
  { name = "Sergio M. Ferro", email = "Sergio_Ferro@epam.com" },
  { name = "Carlo Arias", email = "Carlo_Arias@epam.com" }
]
requires-python = ">=3.9"
dependencies = [
    "kaggle>=1.7.4.5",
    "numpy>=2.0.2",
    "plotly>=6.5.1",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "scipy>=1.12.0",
    "statsmodels>=0.14.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
packages = ["src"]
